# Generated by Django 5.2.8 on 2025-11-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='session',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='sessionmaterial',
            name='session',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='SessionMaterial',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
