# Generated by Django 5.2.8 on 2025-11-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('tutoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutoring_sessions.enrollment'),
        ),
    ]
