# Generated by Django 5.2.8 on 2025-11-23 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_sessionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='note',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='status',
        ),
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(help_text='Description of the technical problem (max 150 characters)', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin/support team', null=True)),
                ('user', models.ForeignKey(help_text='User who reported the issue', on_delete=django.db.models.deletion.CASCADE, related_name='technical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technical Report',
                'verbose_name_plural': 'Technical Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feedback_te_created_7b5801_idx'), models.Index(fields=['status'], name='feedback_te_status_a35e67_idx')],
            },
        ),
    ]
